# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('home', '0005_auto_20170119_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', wagtail.wagtailcore.fields.RichTextField()),
                ('location', wagtail.wagtailcore.fields.RichTextField()),
                ('opening_times', wagtail.wagtailcore.fields.RichTextField()),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
