# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_restaurantinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantInformation',
            new_name='RestaurantInfo',
        ),
    ]
