# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('home', '0008_auto_20170124_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='headline',
            field=models.TextField(default="Giacomo's"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(default="Hello this is Giacomo's'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
