# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 07:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_specials'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='reservation',
            field=wagtail.wagtailcore.fields.RichTextField(default='Hello'),
            preserve_default=False,
        ),
    ]
