# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 07:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(default='hello'),
            preserve_default=False,
        ),
    ]
