# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_menupage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupage',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
