# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170125_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='site_name',
            field=models.TextField(default="Giacomo's Italian Restaurant"),
            preserve_default=False,
        ),
    ]
